### ISSUE TITLE
Other installation methods

### ISSUE THREAD

**Issue by pawamoy** [zunit-zsh/zunit#106]
Hello!

I was hoping you could consider adding installation methods :slightly_smiling_face: 

Currently, the only available installation methods are [Zulu](https://github.com/zulu-zsh/zulu), homebrew and manual installation.

While I like the prompt Zulu set for me, I'm not a fan of programs that change my shell environment without asking. Using homebrew on Linux, even if possible, does not seem so straight-forward.

I know nothing about these, but what about [Zplug](https://github.com/zplug/zplug), [Zgen](https://github.com/tarjoilija/zgen) or [Antigen](https://github.com/zsh-users/antigen)? Do they fill the same purpose as Zulu? Would they be good candidate as installation methods for ZUnit?

Also, coming from Bash, I started to use [Basher](https://github.com/basherpm/basher) for other projects, and like its cleanness and simplicity (it git clones shell projects from providers like github, gitlab, etc.). Basher supports Zsh (and Fish) as well, and I would love to be able to install ZUnit through it. The only problem I see is that ZUnit's installation seems to be in 2 steps: build, then install, which Basher would not support (it only clones stuff, and doesn't execute any custom code). Is the build step mandatory? Couldn't you directly provide the `zunit` executable script in the repo?

**Comment by MichaelAquilina** [comment]
> I know nothing about these, but what about Zplug, Zgen or Antigen? Do they fill the same purpose as Zulu? Would they be good candidate as installation methods for ZUnit?

You should be able to install zunit through `zplug` or any of the these. Here is an example from my zshrc:

https://github.com/MichaelAquilina/swayconfig/blob/master/zshrc#L30-L40

I do agree however that this should be ideally available through a distros package manager. I was considering adding this to the opensuse build service for example.

**Comment by molovo** [comment]
I have actually added [docs for installation with `zplug`](https://zunit.xyz/docs/getting-started/installation/) on the website, I guess I just forgot to add to the README.

**Comment by molovo** [comment]
@pawamoy the Zplug installation steps have now been added to the docs (thanks for the PR)

In response to your other point, the executable and completion file are both available for download for each release on GIthub at https://github.com/zunit-zsh/zunit/releases
