### ISSUE TITLE
'Assertion world does not exist' is not empty    

### ISSUE THREAD

**Issue by psprint** [zunit-zsh/zunit#107]
The CI checks currently fail with error:

```
✘ Test _zunit_assert_contains match

  'Assertion world does not exist' is not empty
```

The test that it refers is:

```
@test 'Test _zunit_assert_contains match' {
  run assert 'hello world' contains 'lo wo'

  assert "$output" is_empty
  assert $state equals 0
}
```

It seems that somehow the second word of the string "hello world" is taken for a name of the assertion to run. What could be causing this?

**Comment by psprint** [comment]
Ah, this is the problem with the complex commands patch, I'll take a look into this

**Comment by psprint** [comment]
The problem was the `extendedglob` option, which I was setting in `~/.zshenv`, and which was missing outside my box.

**Comment by molovo** [comment]
@psprint do you think it would be worth disabling the option within the ZUnit code before the Eval, and then restore the previous state after the Eval is run? This is quite a common option (I use it myself) so I can see quite a few people running into this issue and it's not very obvious that that is the cause

Thanks for finding it by the way, it's been annoying me for weeks!

**Comment by molovo** [comment]
@psprint I see you've already done that. Nice job

**Comment by psprint** [comment]
I didn't do the option saving & restoration before & after `eval`. It is indeed worth doing. I'm thinking about incorporating zplugin's tracking & unloading code, although in a much simplified form: to restore the state recorded before the `eval`, not to compare for differences and withdraw them.
