### ISSUE TITLE
Provide a verbose mode that shows text to stdout/stderr from running commands

### ISSUE THREAD

**Issue by MichaelAquilina** [zunit-zsh/zunit#63]
It's sometimes very difficult to figure out why something has failed from within zunit because there is (that I can tell) no way of displaying the text written to stdout and stderr when running commands.

E.g. if I have `assert $state equals 0` and it fails, it would be nice to see why.

This is especially important if the test is failing on a test CI such as travis but not locally.

**Comment by molovo** [comment]
Totally agree with you there, I've run into that issue myself. I'll add a `--verbose` option to the CLI and `.zunit.yml` in v0.8.0

**Comment by MichaelAquilina** [comment]
Awesome :) Looking forward to that
