### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by psprint** [zunit-zsh/zunit#92]
The project seems to be interesting and enough-invested (>190 commits). But README doesn't provide examples. Can some examples be added?

BTW, maybe you will be interested – there's a tool that parses scripts using Zshell's `(z)` flag and extracts functions. I use it in one project – no need to load whole `crasis` script, instead the extracted functions are autoloaded. The extraction is `zsd-transform`, autoloads are in `runtest.zsh`: https://github.com/zdharma/zplugin-crasis/tree/master/test/bin

**Comment by molovo** [comment]
Did you check the documentation on the website: https://zunit.xyz

Lots of examples on there 

And thanks for the tip about crasis, I'll take a look into it

**Comment by psprint** [comment]
Cool, thanks.

I should write more directly about the function extraction – the point is that it's hard to source whole source of a project because that would cause execution. What is needed are functions to be unit-tested – and `zsd-transform` provides this.
