### ISSUE TITLE
"Missing required dependency" - Potential Regression in zunit 0.8.2?

### ISSUE THREAD

**Issue by MichaelAquilina** [zunit-zsh/zunit#93]
Installing the latest version of zunit seems to be producing a dependency error:

```
$ zunit       
Missing required dependency: Revolver - https://github.com/molovo/revolver
```

However this is installed:
```
$ zplug list | grep -i revolver
molovo/revolver
```

**Comment by molovo** [comment]
Is it definitely in your `$PATH`? That's all it's checking: https://github.com/zunit-zsh/zunit/blob/master/src/zunit.zsh#L61

**Comment by MichaelAquilina** [comment]
Yeah I just noticed that while trying to debug it. I suspect its a regression in my setup. I think its safe to close this considering that

**Comment by MichaelAquilina** [comment]
Might be a regression in zplug. It doesnt seem to be adding $ZPLUG_BIN to $PATH anymore

**Comment by MichaelAquilina** [comment]
Filed an issue here https://github.com/zplug/zplug/issues/453
