### ISSUE TITLE
Coding style – uses forks?

### ISSUE THREAD

**Issue by psprint** [zunit-zsh/zunit#96]
Hello,
I did a quick glance at zunit's source and saw many `sed` and other external programs invocation. An example found by `ack`:

```
src/commands/run.zsh
221:# Encode test name into a value which can be used as a hash key
228:            | sed 's/\- /-/' \
229:            | sed 's/ \-/-/' \
```
The project might already be very important, I often think about using it after positive experience with Bash `BATS`, however such coding style is IMO a problem, I wouldn't introduce forking-style tool to my projects. BATS probably does the same, but on Bash it is different, there rather is no choice except forking for certain features. On Zsh, one can code like in Ruby and other "real" programming languages. I've made a handbook explaining the no-fork way: [Zsh Native Scripting Handbook](http://zdharma.org/Zsh-100-Commits-Club/Zsh-Native-Scripting-Handbook.html).

The project seems to be inactive – I see it has been implemented, works, so no new commits appear. I'm thinking in engageing into zunit, but would you accept no-fork-replacements versions of existing code in pull requests?

**Comment by molovo** [comment]
@psprint Hi there. The project is definitely alive, and I'm using it regularly, I just haven't needed to add any new features for a while. I'd absolutely accept pull requests, and would even support a major version bump provided the changes warrant it. PRs to the `next` branch please.

FYI, that handbook is a very useful resource, I've bookmarked it already. Thanks for putting it together.

**Comment by psprint** [comment]
Great, it will be my following cool project to work on, after I will somewhat finish with fast-syntax-highlighting. Good that the project is active, I think a "suite" could be created for Zsh: zunit – tests, zshelldoc – Doxygen-like docs, ???. The third position, maybe shfmt or something similar, if it doesn't work with all Zsh syntaxes.

**Comment by molovo** [comment]
I like the idea - a suite was always in the back of my mind when I built zunit. I did start work on [a linter](https://github.com/molovo/zlint) but abandoned it as the method I was using (regex matching) was too naive to work properly with ZSH. We need some kind of AST to be able to support that unfortunately, and I don't have the knowledge to build one.

**Comment by psprint** [comment]
I have the idea from [this blog post](https://oscarforner.com/2018/02/24/Software_development_using_Bash), when I looked how author equipped his bash-work with quite good quality tools, I've then got the "suite" idea. There's a linter for Bash apparently, maybe could fork it and easily (hopefully) adapt and extend to Zshell? It may be using AST.

I've recalled that I [also did ctags](https://github.com/psprint/zcommodore/commits/master/myctags), I've extended it to support variables, also multiple variables when defined with single `local`, `typeset`, etc., also when such variable is immediately assigned. Then, files aren't required to have `*.sh` or `*.zsh` extensions, because the ctags looks at emacs and vim modelines in first or last lines. I gave about 8 hours for all those updates, we could make it 16 more (2 days) and I wonder what would be extended. The enthusiasm to `ctags` might be misleading, I didn't use it even once to help my development, however, if that `ctags` will be part of larger suite, then maybe it will be like "naturally" used, in harmony, something like that.

If we decided to do the zsh-suite ecosystem, then maybe someone should register `zsh-suite` organization on Github?

**Comment by psprint** [comment]
I've worried that someone might read the conversation and register `zsh-suite` first, so I've created this organization today. Sent you invite.

**Comment by psprint** [comment]
Hello, should I proceed in making some moves (like building z-ctags project from what's already there) or maybe you would want to withdraw?

Following presents the custom ctags, they can be used directly from Zsh: https://asciinema.org/a/WkP3JV6rlVenqNolU1AuPLcJS. Basically we would have 3 elements in zsh-suite at the very start, I think that's much.
